version: "3.7"
services:
  app:
    build:
      # args:
      #   rootpwd: root
      context: ./
      dockerfile: Dockerfile
    container_name: spark_docker
    # ports:
    #   - 8080:8080
    working_dir: /var/spark_docker/
    volumes:
      - ./src:/var/spark_docker/src


# docker container exec -it spark_docker /bin/sh

