dq_master_site:
  target:
    # <<: *src_mariadb
    database: datamart_actual
    table: master_site
  measure:
    timeliness:
      date_column: site_updated
      date_format: "%Y-%m-%d"
      expected_delivery: "days:-1"
    completeness:
      date_checked: "days:-1"
      dq_rules:
        site_id: "(site_id IS NOT NULL AND site_id RLIKE '([A-Z]{3})([0-9]{3})')"
        site_name: "site_name IS NOT NULL"
        longitude: "longitude BETWEEN 94 AND 142"
        latitude: "latitude BETWEEN -12 AND 7"
        regional_name: "regional_name LIKE 'R%'"
        nsa_name: "nsa_name IS NOT NULL"
        rtpo_name: "rtpo_name IS NOT NULL"
        address: "address IS NOT NULL"

dq_master_site_datamart:
  target:
    # <<: *src_mariadb
    database: datamart_actual
    table: master_site_datamart
  measure:
    timeliness:
      date_column: site_updated
      date_format: "%Y-%m-%d"
      expected_delivery: "days:-1"
    completeness:
      date_checked: "days:-1"
      dq_rules:
        site_id: "(site_id IS NOT NULL AND site_id RLIKE '([A-Z]{3})([0-9]{3})')"